# -*- coding: utf-8 -*-
"""Week3

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vRlKeMb3P6_077LJGGEhGh72k3I6PYpS
"""

import numpy as np
from scipy.spatial import distance
pointA=np.array([2,4,6])
pointB=np.array([5,1,9])
euclidean_dist=distance.euclidean(pointA,pointB)
print("Euclidean Distance:",euclidean_dist)
similarity_euclidean=1/(1+euclidean_dist)
print("Euclidean Similarity:",similarity_euclidean)

import numpy as np
from scipy.spatial import distance
pointA=np.array([2,4,6,8])
pointB=np.array([5,1,9,3])
manhattan_dist=distance.cityblock(pointA,pointB)
print("Manhattan Distance:",manhattan_dist)
similarity_manhattan=1/(1+manhattan_dist)
print("Manhattan Similarity:",similarity_manhattan)

import numpy as np
from scipy.spatial import distance
pointA=np.array([2,4,6,8])
pointB=np.array([5,1,9,3])
minkowski_dist_p3=distance.minkowski(pointA,pointB,p=3)
print("Minkowski Distance(p=3):",minkowski_dist_p3)
similarity_minkowski=1/(1+minkowski_dist_p3)
print("Minkowski Similarity (p=3):",similarity_minkowski)

import numpy as np
from scipy.spatial import distance
pointA=np.array([2,4,6])
pointB=np.array([5,1,9])
minkowski_dist_p1=distance.minkowski(pointA,pointB,p=1)
print("Minkowski Distance(p=1):",minkowski_dist_p1)
similarity_minkowski=1/(1+minkowski_dist_p1)
print("Minkowski Similarity (p=1):",similarity_minkowski)

import numpy as np
from scipy.spatial import distance
pointA=np.array([2,4,6])
pointB=np.array([5,1,9])
euclidean_dist=distance.euclidean(pointA,pointB)
print("Euclidean Distance:",euclidean_dist)
similarity_euclidean=1/(1+euclidean_dist)
print("Euclidean Similarity:",similarity_euclidean)
manhattan_dist=distance.cityblock(pointA,pointB)
print("Manhattan Distance:",manhattan_dist)
similarity_manhattan=1/(1+manhattan_dist)
print("Manhattan Similarity:",similarity_manhattan)
minkowski_dist_p1=distance.minkowski(pointA,pointB,p=1)
print("Minkowski Distance(p=1):",minkowski_dist_p1)
similarity_minkowski=1/(1+minkowski_dist_p1)
print("Minkowski Similarity (p=1):",similarity_minkowski)
minkowski_dist_p3=distance.minkowski(pointA,pointB,p=3)
print("Minkowski Distance(p=3):",minkowski_dist_p3)
similarity_minkowski=1/(1+minkowski_dist_p3)
print("Minkowski Similarity (p=2):",similarity_minkowski)
minkowski_dist_p2=distance.minkowski(pointA,pointB,p=2)
print("Minkowski Distance(p=2):",minkowski_dist_p2)
similarity_minkowski=1/(1+minkowski_dist_p2)
print("Minkowski Similarity (p=2):",similarity_minkowski)

import pandas as pd
df=pd.DataFrame({
    'X':[10,20,30,40,50],
    'Y':[12,24,33,45,60]
})
corr_matrix=df.corr(method='pearson')
print("Pearson Correlation Matrix:\n",corr_matrix)

import pandas as pd
df=pd.DataFrame({
    'DS':[10,20,30,40,50,33],
    'TOC':[12,24,33,45,60,76],
    'SOA':[30,40,50,80,20,60]
})
corr_matrix=df.corr(method='pearson')
print("Pearson Correlation Matrix:\n",corr_matrix)

import pandas as pd
df=pd.read_csv("Iris.csv")
print(df.corr(method='pearson',numeric_only=float))

import pandas as pd
from scipy.stats import spearmanr
df=pd.DataFrame({
     'X':[10,20,30,40,50],
    'Y':[12,24,33,45,60]
})
corr_value,p_value=spearmanr(df['X'],df['Y'])
print(f"Spearman Correlation Coefficient:(corr_value)")
print(f"p_value:{p_value}")

import pandas as pd
df=pd.read_csv("Iris.csv")
print(df.corr(method='spearman',numeric_only=float))

def hamming_distance(str1, str2):
    if len(str1) != len(str2):
        raise ValueError("Strings must be of equal length")
    return sum(ch1 != ch2 for ch1, ch2 in zip(str1, str2))
s1 = "karolin"
s2 = "kathrin"
dist = hamming_distance(s1, s2)
print(f"Hamming Distance between '{s1}' and '{s2}': {dist}")

def lcs_length(X, Y):
    m, n = len(X), len(Y)
    dp = [[0] * (n + 1) for _ in range(m + 1)]
    for i in range(m):
        for j in range(n):
            if X[i] == Y[j]:
                dp[i + 1][j + 1] = dp[i][j] + 1
            else:
                dp[i + 1][j + 1] = max(dp[i][j + 1], dp[i + 1][j])
    return dp[m][n]
seq1 = "ABCDEF"
seq2 = "AEBDF"
length = lcs_length(seq1, seq2)
print(f"Longest Common Subsequence length between '{seq1}' and '{seq2}': {length}")

def jaccard_index1(str1,str2):
  set1,set2=set(str1.split()),set(str2.split())
  intersection=set1.intersection(set2)
  union=set1.union(set2)
  return len(intersection)/len(union)
  s1="Data science"
  s2=" science makes data useful"
  print("Jaccard Index:",jaccard_index(s1,s2))