# -*- coding: utf-8 -*-
"""Week 4

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10UPFJwu7yyG4ifklANJ3BccOhogHlqLo
"""

pip install seaborn

!pip install seaborn

import seaborn as sns
tips=sns.load_dataset("tips")
print(tips.head())

import seaborn as sns
iris=sns.load_dataset("iris")
print(iris.head())

import seaborn as sns
titanic=sns.load_dataset("titanic")
print(titanic.head())

import seaborn as sns
df=sns.load_dataset("titanic")
print("Data shape:",df.shape)
print(df.head())

import seaborn as sns
df=sns.load_dataset("titanic")
print("Data shape:",df.shape)
print(df.head())
print(df.info())
print(df.describe())

import seaborn as sns
df = sns.load_dataset("titanic")
df['age'] = df['age'].fillna(df['age'].median())
df['embarked'] = df['embarked'].fillna(df['embarked'].mode()[0])
df.drop_duplicates(inplace=True)
df = pd.get_dummies(
    df,
    columns=['sex', 'class', 'embarked'],
    drop_first=True
)
df['family_size'] = df['sibsp'] + df['parch']
print(df.head())

import pandas as pd
df = pd.read_csv("student.csv")
df['Age'] = df['Age'].fillna(df['Age'].median())
df['Attendance'] = df['Attendance'].fillna(df['Attendance'].median())
df['Math_Score'] = df['Math_Score'].fillna(df['Math_Score'].median())
df['Science_Score'] = df['Science_Score'].fillna(df['Science_Score'].median())
df.drop_duplicates(inplace=True)
df = pd.get_dummies(df,columns=['Gender','Department','City'],drop_first=True)
print(df.head())

import matplotlib.pyplot as plt
import seaborn as sns
sns.histplot(df['Age'],bins=20,kde=True)
plt.title("Age Distribution")
plt.show()

import matplotlib.pyplot as plt
import seaborn as sns
df=sns.load_dataset("titanic")
sns.histplot(df['age'],bins=10,kde=True)
plt.title("Age Distribution")
plt.show()

import matplotlib.pyplot as plt
import seaborn as sns
df=sns.load_dataset("titanic")
sns.histplot(df['age'],bins=10,kde=True)
plt.title("Age Distribution")
plt.show()
df=sns.load_dataset("tips")
sns.histplot(df['size'],bins=10,kde=True)
plt.title("Age Distribution")
plt.show()

import matplotlib.pyplot as plt
import seaborn as sns
df=pd.read_csv("student.csv")
sns.histplot(df['Attendance'],bins=10,kde=True)
plt.title("Attendance")
plt.show()

objective = "Classification: Survied (Yes/No)"
success_criteria = "Accuracy > 80%"
constraints = "Limited features, miising value,imbalanced classes"
print("Objective:",objective)
print("Sucess Criteria:",success_criteria)
print("Constraints:",constraints)

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
corr=df.corr(numeric_only=True)
print(corr)
sns.heatmap(corr,annot=True,cmap='coolwarm')
plt.title("Correlation Matrix")
plt.show()

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
df = sns.load_dataset("tips")
corr=df.corr(numeric_only=True)
print(corr)
sns.heatmap(corr,annot=True,cmap="coolwarm")
plt.title("Correlation Matrix")
plt.show()