# -*- coding: utf-8 -*-
"""Week7

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PbiTirkvITTXrBoG78jnrSSKA0zPOAkY
"""

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.datasets import load_iris

iris = load_iris()
df = pd.DataFrame(iris.data, columns=iris.feature_names)
df['species'] = iris.target

plt.figure(figsize=(6,4))
sns.histplot(df['sepal length (cm)'], bins=20, kde=True)
plt.show()

plt.figure(figsize=(6,4))
sns.boxplot(x=df['sepal length (cm)'])
plt.title("Boxplot of sepal length")
plt.show()

species_counts = df['species'].value_counts()
plt.figure(figsize=(6,6))
plt.pie(species_counts, labels=iris.target_names, autopct='%1.1f%%')
plt.title("Species Distribution (Pie Chart)")
plt.show()

plt.figure(figsize=(6,4))
sns.scatterplot(x=df['sepal length (cm)'],y=df['sepal width (cm)'],hue=df['species'])
plt.title("Scatterplot: Sepal Length vs Sepal Width")
plt.show()
plt.figure(figsize=(6,4))
plt.plot(df['sepal length (cm)'])
plt.title("Line Chart of Sepal Length")
plt.xlabel("Sample Index")
plt.ylabel("Sepal Length (cm)")
plt.show()
plt.figure(figsize=(6,4))
sns.barplot(x=df['species'],y=df['sepal length (cm)'])
plt.title("Bar Chart: Mean Sepal Length by Species")
plt.xticks([0,1,2], iris.target_names)
plt.show()

plt.figure(figsize=(8,6))
sns.heatmap(df.iloc[:,:4].corr(), annot=True, cmap="coolwarm")
plt.title("Heatmap of Feature Correlations")
plt.show()
plt.figure(figsize=(6,4))
plt.scatter(df['sepal length (cm)'], df['sepal width (cm)'],
            s=df['petal length (cm)']*20, alpha=0.5, c=df['species'])
plt.title("Bubble Chart: Sepal vs Petal (size=petal length)")
plt.xlabel("Sepal Length (cm)")
plt.ylabel("Sepal Width (cm)")
plt.show()
sns.pairplot(df.iloc[:,:4])
plt.suptitle("Pair Plot of Iris Features", y=1.02)
plt.show()

plt.figure(figsize=(6,4))
sns.violinplot(x=df['species'], y=df['sepal length (cm)'])
plt.title("Violin Plot: Sepal Length by Species")
plt.xticks([0,1,2],iris.target_names)
plt.show()

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

tips = sns.load_dataset("tips")

plt.figure(figsize=(6,4))
sns.scatterplot(x=tips['total_bill'], y=tips['tip'], hue=tips['day'])
plt.title("Scatterplot: Total Bill vs Tip")
plt.show()

plt.figure(figsize=(6,4))
plt.plot(tips['total_bill'])
plt.title("Line Chart of Total Bill")
plt.xlabel("Sample Index")
plt.ylabel("Total Bill ($)")
plt.show()

plt.figure(figsize=(6,4))
sns.barplot(x=tips['day'], y=tips['total_bill'])
plt.title("Bar Chart: Mean Total Bill by Day")
plt.show()

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

tips = sns.load_dataset("tips")

plt.figure(figsize=(6,4))
sns.histplot(tips['total_bill'], bins=20, kde=True)
plt.title("Histogram of Total Bill")
plt.show()

plt.figure(figsize=(6,4))
sns.boxplot(x=tips['total_bill'])
plt.title("Boxplot of Total Bill")
plt.show()

day_counts = tips['day'].value_counts()
plt.figure(figsize=(6,6))
plt.pie(day_counts, labels=day_counts.index, autopct='%1.1f%%')
plt.title("Day Distribution (Pie Chart)")
plt.show()

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

tips = sns.load_dataset("tips")

plt.figure(figsize=(6,4))
sns.violinplot(x=tips['day'], y=tips['total_bill'])
plt.title("Violin plot: Total Bill by Day")
plt.show()

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

tips = sns.load_dataset("tips")

plt.figure(figsize=(8,6))
sns.heatmap(tips.corr(numeric_only=True), annot=True, cmap="coolwarm")
plt.title("Heatmap of feature correlations")
plt.show()

plt.figure(figsize=(6,4))
plt.scatter(tips['total_bill'], tips['tip'], s=tips['size']*20, alpha=0.5, c=tips['size'])
plt.title("Bubble chart: Total Bill vs Tip (size = party size)")
plt.xlabel("Total Bill ($)")
plt.ylabel("Tip ($)")
plt.show()

sns.pairplot(tips[['total_bill','tip','size']])
plt.suptitle("Pair plot of tips dataset", y=1.02)
plt.show()