# -*- coding: utf-8 -*-
"""Week 6

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iCYNuze2VU5egUgJxC_zBQvD1cdVve1L
"""

import pandas as pd
from sklearn.datasets import load_iris
from statistics import mode
iris=load_iris()
df=pd.DataFrame(iris.data,columns=iris.feature_names)
print("First 5 rows of dataset:")
print(df.head())
mean_values=df.mean()
print("\nMean values:")
print(mean_values)
median_values=df.median()
print("\nMedian values:")
print(median_values)
mode_values=df.mode().iloc[0]
print("\nMode values:")
print(mode_values)

import pandas as pd
import seaborn as sns
tips=sns.load_dataset("tips")
print("First 5 rows of dataset:")
print(df.head())
mean_values=df.mean()
print("\nMean values:")
print(mean_values)
median_values=df.median()
print("\nMedian values:")
print(median_values)
mode_values=df.mode().iloc[0]
print("\nMode values:")
print(mode_values)

import pandas as pd
from sklearn.datasets import load_iris
from statistics import mode
iris=load_iris()
df=pd.DataFrame(iris.data,columns=iris.feature_names)
print("First 5 rows of dataset:")
print(df.head())
range_values=df.max()-df.min()
print("\nRange values:")
print(range_values)
variance_values=df.var()
print("\nVariance values:")
print(variance_values)
std_values=df.std()
print("\nStandard Deviation values:")
print(std_values)
Q1=df.quantile(0.25)
Q3=df.quantile(0.75)
IQR=Q3-Q1
print("\nInterquartile Range (IQR):")
print(IQR)

import pandas as pd
import seaborn as sns
tips=sns.load_dataset("tips")
print("First 5 rows of dataset:")
print(df.head())
range_values=df.max()-df.min()
print("\nRange values:")
print(range_values)
variance_values=df.var()
print("\nVariance values:")
print(variance_values)
std_values=df.std()
print("\nStandard Deviation values:")
print(std_values)
Q1=df.quantile(0.25)
Q3=df.quantile(0.75)
IQR=Q3-Q1
print("\nInterquartile Range (IQR):")
print(IQR)

import pandas as pd
from sklearn.datasets import load_iris
iris=load_iris()
df=pd.DataFrame(iris.data,columns=iris.feature_names)
print("First 5 rows of dataset:")
print(df.head())
skewness_values=df.skew()
print("\nSkewness values:")
print(skewness_values)
kurtosis_values=df.kurt()
print("\nKurtosis values:")
print(kurtosis_values)

import pandas as pd
import seaborn as sns
tips=sns.load_dataset("tips")
print("First 5 rows of dataset:")
print(df.head())
skewness_values=df.skew()
print("\nSkewness values:")
print(skewness_values)
kurtosis_values=df.kurt()
print("\nKurtosis values:")
print(kurtosis_values)